services:
  db:
    profiles:
      - dev
      - prod
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roboclaim
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - roboclaim

  pgadmin:
    profiles:
      - dev
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - roboclaim

  cache:
    profiles:
      - dev
      - prod
    image: redis:7.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - roboclaim

  server:
    profiles:
      - prod
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
      NODE_ENV: production
      JWT_SECRET: secret
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
      DATABASE_NAME: roboclaim
      REDIS_HOST: cache
      REDIS_PORT: 6379
      PORT: 4000
    depends_on:
      - db
      - cache
    networks:
      - roboclaim

  web:
    profiles:
      - prod
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      NEXT_PUBLIC_API_URL: http://localhost:4000
      API_URL: http://server:4000
      NEXTAUTH_SECRET: secret
      NEXTAUTH_URL: http://localhost:3000
    networks:
      - roboclaim


volumes:
  pgdata:
  redisdata:

networks:
  roboclaim:
    driver: bridge
