services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roboclaim
    ports:
      - 5432:5432
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - default

  cache:
    image: redis:7.4
    restart: always
    ports:
      - 6379:6379
    networks:
      - default

networks:
  default:
    driver: bridge
